WvnNCVT=case_when(WovenNestCanopyVegTypes%in%c("Spartina patens","SPARTINA PATENS")~"patens",
                  WovenNestCanopyVegTypes%in%c("Spartina alterniflora","SPARTINA ALTERNIFLORA")~"alterniflora",
                  WovenNestCanopyVegTypes%in%c("Juncus geradii","Juncus gerardii","JUNCUS GERARDII")~"juncus",
                  WovenNestCanopyVegTypes%in%c("Spartina patens;Distichlis spicata","Distichlis spicata;Spartina patens")~"patens;distichlis",
                  WovenNestCanopyVegTypes%in%c("Spartina alterniflora;Spartina patens","Spartina patens;Spartina alterniflora","SPARTINA ALTERNIFLORA;SPARTINA PATENS")~"patens;alterniflora",
                  WovenNestCanopyVegTypes%in%c("Spartina alterniflora;Juncus gerardii","Juncus gerardii;Spartina alterniflora","Juncus geradii;Spartina alterniflora")~"juncus;alterniflora",
                  WovenNestCanopyVegTypes%in%c("Spartina alterniflora;Distichlis spicata","Spartina alterniflora;Distichils spicata","Distichlis spicata;Spartina alterniflora")~"distichlis;alterniflora",
                  WovenNestCanopyVegTypes%in%c("Spartina alterniflora;Spartina patens;Distichlis spicata","Spartina alterniflora;Distichlis spicata;Spartina patens","Spartina patens;Spartina alterniflora;Distichlis spicata","Spartina patens;Distichlis spicata;Spartina alterniflora","Distichlis spicata;Spartina patens;Spartina alterniflora","Distichlis spicata;Spartina alterniflora;Spartina patens")~"patens;distichlis;alterniflora",
                  WovenNestCanopyVegTypes%in%c("Distichlis spicata;Spartina alterniflora;Juncus gerardii","Spartina alterniflora;Distichlis spicata;Juncus gerardii","Distichlis spicata;Juncus gerardii;Spartina alterniflora")~"distichlis;juncus;alterniflora",
                  WovenNestCanopyVegTypes%in%c("Spartina patens;Lysimachia maritima","Lysimachia maritima;Spartina patens")~"patens;lysimachia",
                  WovenNestCanopyVegTypes%in%c("Wrack;Spartina alterniflora;Spartina patens","Spartina alterniflora;Spartina patens;Wrack")~"patens;alterniflora;wrack",
                  WovenNestCanopyVegTypes=="Phragmites australis;Spartina patens"~"phragmites;patens",
                  WovenNestCanopyVegTypes=="Spartina patens;Distichlis spicata;Spartina alterniflora;Juncus geradii"~"patens;distichlis;alterniflora;juncus",
                  WovenNestCanopyVegTypes=="Juncus geradii;Distichlis spicata"~"juncus;distichlis",
                  WovenNestCanopyVegTypes=="Spartina alterniflora;Spartina patens;Limonium carolinianum"~"patens;alterniflora;limonium",
                  WovenNestCanopyVegTypes=="Spartina patens;Spartina pectinata"~"patens;pectinata",
                  WovenNestCanopyVegTypes=="Juncus gerardii;Phragmites australis"~"juncus;phragmites",
                  WovenNestCanopyVegTypes=="Juncus gerardii;Triglochin maritima"~"juncus;triglochin",
                  WovenNestCanopyVegTypes=="Distichlis spicata;Wrack"~"distichlis;wrack",
                  WovenNestCanopyVegTypes=="Spartina alterniflora;Wrack"~"alterniflora;wrack",
                  WovenNestCanopyVegTypes=="Phragmites australis;Spartina alterniflora"~"phragmites;alterniflora",
                  is.na(WovenNestCanopyVegTypes)~WovenNestCanopyVegTypes
)